# Default config file

# For sending reports to email
email:
  to: ""                    # Receiver Email Address
  from: ""                     # Sender Email Address
  smtp_host: ""                    # SMTP Host Address
  smtp_port: 587                                    # SMTP PORT, 465 (SSL), 587(Legacy) or 25 (some providers block port 25)
  smtp_ssl: False                                   # IF Smtp_port is 465 then set smtp_ssl to True
  username: ""
  password: ""
  subject: "Data Profiling"
csv:
  modeling:
    file: "Churn-Modeling.csv"    # Data file must be present in user-data folder of project
  health:
    file: "Big_Cities_Health_Data_Inventory.csv"
json:
  test:
    file: "example.json"   # Data file must be present in user-data  folder of project

mysql:
  test:                      # name must be data base name
    host: "127.0.0.1"
    username: "cm9vdA=="
    password: ""
    port: "3306"

servicenow:
  vodafonedev4:                  # name must be ServiceNow instance name
    username: "c2hhaGJhei5hbGlAY2xvdWRpbnAuY29t"
    password: "Um95YWxARmFsY29uXzAz"
  dev58733:
    username: "YWRtaW4="
    password: "eGJBZER5OWYqQlo4OUJEel5GcFQ4dis/azw6K281"
