# Default config file

# For sending reports to email
email:
  to: "shahbaz.ali@cloudinp.com"
  smtp_host: "smtp.gmail.com"
  smtp_port: 465
  smtp_starttls: True
  smtp_ssl: False
  username: "shahbaz.ali03@gmail.com"
  password: "ryfczhpcdsfwybjc"
  subject: "Data Profiling"