# Default config file

# For sending reports to email
email:
  to: ""                    # Receiver Email Address
  from: ""                     # Sender Email Address
  smtp_host: ""                    # SMTP Host Address
  smtp_port: 587                                    # SMTP PORT, 465 (SSL), 587(Legacy) or 25 (some providers block port 25)
  smtp_ssl: False                                   # IF Smtp_port is 465 then set smtp_ssl to True
  username: ""
  password: ""
  subject: "Data Profiling"
mysql:
  dev:
    host: "127.0.0.1"
    username: "YWtlZWwK"
    password: "YWtlZWwK"
    port: "3306"

  prod:
    host: "127.0.0.1"
    username: "YWtlZWwK"
    password: "YWtlZWwK"
    port: "3306"