# Default config file

# For sending reports to email
email:
  to: ""                    # Receiver Email Address
  from: ""                     # Sender Email Address
  smtp_host: ""                    # SMTP Host Address
  smtp_port: 587                                    # SMTP PORT, 465 (SSL), 587(Legacy) or 25 (some providers block port 25)
  smtp_ssl: False                                   # IF Smtp_port is 465 then set smtp_ssl to True
  username: ""
  password: ""
  subject: "Data Profiling"
csv:
  example:
    file: "example.csv",    # Data file must be present in user-data folder of project
json:
  test:
    file: "example.json",   # Data file must be present in user-data  folder of project

mysql:
  dev:                      # name must be data base name
    host: "localhost"
    username: "root"
    password: ""
    port: "3306"

servicenow:
  dev1234:                  # name must be ServiceNow instance name
    username: ""
    password: ""