# Default config file

# For sending reports to email
email:
  to: ""                    # Receiver Email Address
  from: ""                     # Sender Email Address
  smtp_host: ""                    # SMTP Host Address
  smtp_port: 587                                    # SMTP PORT, 465 (SSL), 587(Legacy) or 25 (some providers block port 25)
  smtp_ssl: False                                   # IF Smtp_port is 465 then set smtp_ssl to True
  username: ""
  password: ""
  subject: "Data Profiling"

# Data Masking settings

encryption:
  type: "caesar"            # Default encryption type to be used for data_masking
  key: "CloudTDMS@2020"     # Default encryption key to be used for data_masking

mask:
  with: "x"                 # Default masking character
  characters: 6             # Default masking length
  from: "mid"               # Default masking alignment

# Source and Destination Connections

# Local Static File Connections

# CSV
csv:
  test_data:          # Connection Name
    source: ""        # source is usually a path to CSV data file
    target: ""        # target is usually a path to local folder where data must be saved

# JSON
json:
  test_data:          # Connection Name
    source: ""        # source is usually a path to CSV data file
    target: ""        # target is usually a path to local folder where data must be saved

# Database Connections

# MySQL
mysql:
  mysql_test:         # Connection Name
    host: "127.0.0.1"          # MySQL host name
    database: "dev"      # MySQL database name
    username: "YWtlZWwK"      # MySQL username Base64 Encrypted
    password: "YWtlZWwK"      # MySQL password Base64 Encrypted
    port: "3306"      # MySQL port default is 3306

# Postgres
postgres:
  postgres_test:      # Connection Name
    host: "127.0.0.1"          # Postgres host name
    database: "dev"      # Postgres database name
    username: "cG9zdGdyZXMK"      # Postgres username Base64 Encrypted
    password: "cG9zdGdyZXMK"      # Postgres password Base64 Encrypted
    port: "5432"      # Postgres port default is 5432

# MSSQL
mssql:
  mssql_test:           # Connection Name
    host: "127.0.0.1"            # MSSQL host name
    database: "dev"        # MSSQL database name
    username: "U0EK"        # MSSQL user name Base64 Encrypted
    password: "YWtlZWxAMTIzCg=="        # MSSQL password Base64 Encrypted
    port: "1433"        # MSSQL port default is 1433

# Network Storages

# SFTP
sftp:
  sftp_test:          # Connection Name
    host: "40.117.252.42"          # SFTP host name
    username: "TXVoYW1tYWRfQWtlZWwK"      # SFTP login name Base64 Encrypted
    password: ""      # SFTP login password Base64 Encrypted
    port: "22"          # SFTP port
    ssh_public_key: "/home/muhammad/.ssh/ssh_key.pub"  # path to ssh public key
    passphrase: "YWtlZWxAMzIwNAo="


# SAAS Platforms

# ServiceNow
servicenow:
  production:
    host: "dev97751"
    username: "YWRtaW4="
    password: "YVRvWGV3NjlnTkRG"
  development:
    host: "dev58733"
    username: "YWRtaW4="
    password: "eGJBZER5OWYqQlo4OUJEel5GcFQ4dis/azw6K281"





#sftp password :bXVoYW1tYWRha2VlbEAzMjA0Cg==