version: "3"
services:

  webserver:
    build: .
    command: "webserver"
    environment:
      - AIRFLOW_HOME=/opt/airflow/system
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/system/dags
      - AIRFLOW__CORE__BASE_LOG_FOLDER=/opt/airflow/system/logs
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
    - ./system/dags:/opt/airflow/system/dags
    - ./system/airflow.cfg:/opt/airflow/system/airflow.cfg
    - ./system/logs:/opt/airflow/system/logs
    - ./system/airflow.db:/opt/airflow/system/airflow.db
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./user-data:/opt/airflow/user-data
    ports:
    - "8080:8080"
  scheduler:
    build: .
    command: "scheduler"
    environment:
      - AIRFLOW_HOME=/opt/airflow/system
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/system/dags
      - AIRFLOW__CORE__BASE_LOG_FOLDER=/opt/airflow/system/logs
    volumes:
      - ./system/dags:/opt/airflow/system/dags
      - ./system/airflow.cfg:/opt/airflow/system/airflow.cfg
      - ./system/logs:/opt/airflow/system/logs
      - ./system/airflow.db:/opt/airflow/system/airflow.db
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./user-data:/opt/airflow/user-data