version: "3"
services:

  scheduler:
    build: .
    command: "scheduler"
    environment:
      - AIRFLOW_HOME=/opt/cloudtdms/system
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/cloudtdms/system/dags
      - AIRFLOW__CORE__BASE_LOG_FOLDER=/opt/cloudtdms/system/logs
#    healthcheck:
#      test: ["CMD-SHELL", "[ -f /opt/cloudtdms/airflow-webserver.pid ]"]
#      interval: 30s
#      timeout: 30s
#      retries: 3
    volumes:
    - .:/opt/cloudtdms
    - ./config:/opt/cloudtdms/config
    - ./data:/opt/cloudtdms/data
    - ./user-data:/opt/cloudtdms/user-data
    - ./profiling_reports:/opt/cloudtdms/profiling_reports
    - ./profiling_data:/opt/cloudtdms/profiling_data
    ports:
    - "8080:8080"

